[package]
name = "emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.7.1"
eframe = {version = "0.31.1", features = ["default"]}
common = { path = "../common" }
assembler = { path = "../assembler"}
disassembly = { path = "../disassembly" }
